### ISSUE TITLE
Clean the padding area

### ISSUE THREAD

**Issue by mpancorbo** [odzhan/sha3#1]
I think there is an error in `SHA3_Final` function. The block memory area between `index` and `blklen` should firstly be cleaned up with 0'es, and then apply the bit addition:

    /**** Here ****/
    memset(ctx->blk + ctx->index, 0, ctx->blklen - ctx->index);
    /**************/
    ctx->blk[ctx->index] = 6;
    // or the end bit
    ctx->blk[ctx->blklen-1] |= 0x80;

This way the padding of original message is applied as NIST draft indicates.

**Comment by odzhan** [comment]
Thank you for reporting this to me, I've updated sources.
